name: Scheduler Test2

on:
  workflow_dispatch:        # ✅ This should be here
  schedule:
    - cron: "*/5 * * * *"   # ✅ This should be here

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GitHub Scheduler Works!"